# fly.toml app configuration file generated for pixel-canvas on 2025-09-18T20:16:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pixel-canvas'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
  memory_mb = 4096
